---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: download-extract-commit
spec:
  params:
  - name: blueprintName
    type: string
  - name: apiEndpoint
    type: string
  - name: composeMetadata
    type: string
  - name: containerImage
    type: string
  steps:
  - command:
    - /usr/bin/bash
    - -c
    - /usr/bin/curl $(params.apiEndpoint)/compose/image/$(/usr/bin/jq -r '.build_id'
      "/workspace/shared-volume/$(params.blueprintName)/$(params.composeMetadata)") --output "/workspace/shared-volume/$(params.blueprintName)/edge-commit.tar"
      --verbose
    image: $(params.containerImage)
    name: download
  - command:
    - /usr/bin/bash
    - -c
    - tar xf /workspace/shared-volume/$(params.blueprintName)/edge-commit.tar -C /workspace/shared-volume/$(params.blueprintName)/
    image: $(params.containerImage)
    name: extract-commit
  workspaces:
  - name: shared-volume
  - name: blueprints